### ISSUE TITLE
Upload to Bintray?

### ISSUE THREAD

**Issue by Myk-da-Beast** [sky-uk/gradle-maven-plugin#28] opened 2019-10-28 22:56 UTC
I want to upload to Bintray, can this plugin do that? I see the `mavRemoteRepo` is that what I need to use? If so do I give it the username and password to my bintray account? And what Url do I pass?

**Comment by Fed93** [comment] 2019-10-29 08:03
@Myk-da-Beast in order to upload your library to Bintray you have to use bintray gradle plugin instead of gradle-maven-plugin.
Duplicate of #18

**Comment by gotev** [comment] 2021-04-16 20:37
closing as bintray is sunsetting

**Closed by gotev** 2021-04-16 20:37 UTC
